CREATE TABLE platform_outreach_contacts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL,
  uid VARCHAR(50) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  company_name VARCHAR(255),
  city VARCHAR(100),
  notes TEXT,
  status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  created_by BIGINT,
  updated_by BIGINT,
  PRIMARY KEY (id),
  UNIQUE KEY uk_poc_uuid (uuid),
  UNIQUE KEY uk_poc_uid (uid),
  UNIQUE KEY uk_poc_email (email),
  INDEX idx_poc_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE platform_outreach_templates (
  id BIGINT NOT NULL AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL,
  uid VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  subject VARCHAR(500) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  language VARCHAR(10) NOT NULL DEFAULT 'TR',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  created_by BIGINT,
  updated_by BIGINT,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pot_uuid (uuid),
  UNIQUE KEY uk_pot_uid (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE platform_outreach_campaigns (
  id BIGINT NOT NULL AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL,
  uid VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  template_id BIGINT,
  subject VARCHAR(500) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
  total_count INT NOT NULL DEFAULT 0,
  sent_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  created_by_email VARCHAR(255),
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  created_by BIGINT,
  updated_by BIGINT,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pocamp_uuid (uuid),
  UNIQUE KEY uk_pocamp_uid (uid),
  INDEX idx_pocamp_status (status),
  CONSTRAINT fk_pocamp_template FOREIGN KEY (template_id) REFERENCES platform_outreach_templates(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE platform_outreach_campaign_contacts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL,
  uid VARCHAR(50) NOT NULL,
  campaign_id BIGINT NOT NULL,
  contact_id BIGINT NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  provider_message_id VARCHAR(255),
  error_message TEXT,
  rendered_subject VARCHAR(500),
  rendered_content MEDIUMTEXT,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  created_by BIGINT,
  updated_by BIGINT,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pocc_uuid (uuid),
  UNIQUE KEY uk_pocc_uid (uid),
  INDEX idx_pocc_campaign (campaign_id),
  INDEX idx_pocc_status (status),
  CONSTRAINT fk_pocc_campaign FOREIGN KEY (campaign_id) REFERENCES platform_outreach_campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_pocc_contact FOREIGN KEY (contact_id) REFERENCES platform_outreach_contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
