package com.backend.domain.commerce;

public enum CommerceNotificationEventType {
	ORDER_PAID,
	ORDER_SHIPPED,
	ORDER_REQUEST_CREATED,
	ORDER_REQUEST_APPROVED,
	ORDER_REQUEST_REJECTED,
	ADMIN_ORDER_CREATED,
	ADMIN_ORDER_REQUEST_CREATED,
	ADMIN_PAYMENT_OPERATION_FAILED
}
