CREATE TABLE config_properties (
  id BIGINT NOT NULL AUTO_INCREMENT,
  config_key VARCHAR(255) NOT NULL,
  config_value TEXT NULL,
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_config_properties_config_key (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

