import sharp from "sharp";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const buf = await sharp(join(root, "public/images/photos/hero-v2.jpg"))
  .resize({ width: 20 })
  .webp({ quality: 30 })
  .toBuffer();

const b64 = "data:image/webp;base64," + buf.toString("base64");
writeFileSync(
  join(root, "src/lib/hero-lqip.ts"),
  `// Auto-generated by scripts/gen-lqip.mjs — do not edit manually\nexport const HERO_LQIP = "${b64}";\n`
);
console.log("hero-lqip.ts written,", buf.length, "bytes");
