/**
 * Full image optimization pipeline.
 * Run: node scripts/optimize-all.mjs
 */

import sharp from "sharp";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pub  = join(root, "public");

const JOBS = [
  // Hero
  ["images/photos/hero-v2.jpg",    "images/photos/hero-v2.webp",         1920, 82],
  ["images/photos/hero-v2.jpg",    "images/photos/hero-v2-mobile.webp",   828, 80],

  // About tiles
  ["images/about/platform.jpg",    "images/about/platform.webp",          800, 85],
  ["images/about/multi-lang.jpg",  "images/about/multi-lang.webp",        800, 83],
  ["images/about/database.jpg",    "images/about/database.webp",          800, 83],
  ["images/about/commerce.jpg",    "images/about/commerce.webp",          800, 83],
  ["images/about/saas.jpg",        "images/about/saas.webp",              800, 83],

  // Use-case tabs
  ["images/photos/agency.jpg",     "images/photos/agency.webp",          1280, 82],
  ["images/photos/saas.jpg",       "images/photos/saas.webp",            1280, 82],
  ["images/photos/corporate.jpg",  "images/photos/corporate.webp",       1280, 82],
  ["images/photos/ecommerce.jpg",  "images/photos/ecommerce.webp",       1280, 82],

  // Features
  ["images/photos/planner-texture.jpg", "images/photos/planner-texture.webp", 1200, 82],

  // CTA
  ["images/photos/Yxyz4xAO2Afi4x2mrtShsiVlWA.png", "images/photos/Yxyz4xAO2Afi4x2mrtShsiVlWA.webp", 900, 85],
  ["images/icons/craftive-app.png", "images/icons/craftive-app.webp",    840, 88],

  // Portfolio
  ["images/portfolio/quickalarm.png", "images/portfolio/quickalarm.webp", 900, 85],
  ["images/portfolio/agency.png",     "images/portfolio/agency.webp",     900, 85],
  ["images/portfolio/yemredev.png",   "images/portfolio/yemredev.webp",   900, 85],
];

let totalSaved = 0;

for (const [inRel, outRel, maxW, quality] of JOBS) {
  const inPath  = join(pub, inRel);
  const outPath = join(pub, outRel);

  if (!existsSync(inPath)) { console.warn(`  SKIP (not found): ${inRel}`); continue; }

  await sharp(inPath).resize({ width: maxW, withoutEnlargement: true }).webp({ quality, effort: 6 }).toFile(outPath);

  const origKB = (readFileSync(inPath).length / 1024).toFixed(1);
  const newKB  = (readFileSync(outPath).length / 1024).toFixed(1);
  totalSaved  += readFileSync(inPath).length - readFileSync(outPath).length;
  console.log(`  ${origKB.padStart(7)} KB → ${newKB.padStart(6)} KB  ${outRel}`);
}

// LQIP for hero
const lqipBuf = await sharp(join(pub, "images/photos/hero-v2.jpg")).resize({ width: 20 }).webp({ quality: 30 }).toBuffer();
writeFileSync(
  join(root, "src/lib/hero-lqip.ts"),
  `// Auto-generated by scripts/optimize-all.mjs — do not edit manually\nexport const HERO_LQIP = "data:image/webp;base64,${lqipBuf.toString("base64")}";\n`
);
console.log(`\n  hero-lqip.ts written (${lqipBuf.length} bytes)`);
console.log(`\nTotal saved: ${(totalSaved / 1024 / 1024).toFixed(1)} MB`);
