CREATE TABLE commerce_checkouts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    cart_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    currency_iso VARCHAR(3) NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vat_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    shipping_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    shipping_method_code VARCHAR(50) NOT NULL,
    shipping_method_name VARCHAR(100) NOT NULL,
    delivery_address_uid VARCHAR(50) NOT NULL,
    billing_address_uid VARCHAR(50) NOT NULL,
    delivery_address_snapshot JSON NOT NULL,
    billing_address_snapshot JSON NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_checkout_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_checkout_uid UNIQUE (uid),
    CONSTRAINT fk_commerce_checkout_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_commerce_checkout_cart FOREIGN KEY (cart_id)
        REFERENCES commerce_carts(id) ON DELETE RESTRICT,
    INDEX idx_commerce_checkout_customer_status_expires (customer_id, status, expires_at),
    INDEX idx_commerce_checkout_cart (cart_id)
);

CREATE TABLE commerce_checkout_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    checkout_id BIGINT NOT NULL,
    product_uid VARCHAR(50) NOT NULL,
    product_sku VARCHAR(100) NOT NULL,
    variant_uid VARCHAR(50) NOT NULL,
    variant_sku VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    unit_gross_price DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vat_rate DECIMAL(5,2) NOT NULL,
    line_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    line_vat_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_checkout_item_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_checkout_item_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_checkout_item_checkout_variant UNIQUE (checkout_id, variant_uid),
    CONSTRAINT fk_commerce_checkout_item_checkout FOREIGN KEY (checkout_id)
        REFERENCES commerce_checkouts(id) ON DELETE CASCADE,
    INDEX idx_commerce_checkout_item_checkout (checkout_id),
    INDEX idx_commerce_checkout_item_variant_uid (variant_uid)
);
