CREATE TABLE commerce_notification_templates (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    template_key VARCHAR(60) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    language VARCHAR(10) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_commerce_notification_template_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_notification_template_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_notification_template_key_channel_lang UNIQUE (template_key, channel, language),
    INDEX idx_commerce_notification_template_lookup (template_key, channel, language, is_active),
    CONSTRAINT chk_commerce_notification_template_channel CHECK (channel IN ('EMAIL')),
    CONSTRAINT chk_commerce_notification_template_key CHECK (template_key IN (
        'ORDER_PAID',
        'ORDER_SHIPPED',
        'ORDER_REQUEST_CREATED',
        'ORDER_REQUEST_APPROVED',
        'ORDER_REQUEST_REJECTED'
    ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_notification_outbox (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    aggregate_type VARCHAR(40) NOT NULL,
    aggregate_uid VARCHAR(50) NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    language VARCHAR(10) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    provider_message_id VARCHAR(255) NULL,
    error_message TEXT NULL,
    sent_at TIMESTAMP NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_commerce_notification_outbox_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_notification_outbox_uid UNIQUE (uid),
    INDEX idx_commerce_notification_outbox_status_created (status, created_at),
    INDEX idx_commerce_notification_outbox_event_aggregate (event_type, aggregate_uid),
    CONSTRAINT chk_commerce_notification_outbox_channel CHECK (channel IN ('EMAIL')),
    CONSTRAINT chk_commerce_notification_outbox_status CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT chk_commerce_notification_outbox_event CHECK (event_type IN (
        'ORDER_PAID',
        'ORDER_SHIPPED',
        'ORDER_REQUEST_CREATED',
        'ORDER_REQUEST_APPROVED',
        'ORDER_REQUEST_REJECTED'
    ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO commerce_notification_templates (
    uuid,
    uid,
    template_key,
    channel,
    language,
    subject,
    content,
    is_active
)
VALUES
('11111111-1111-4111-8111-000000000001', 'cntpl_order_paid_tr', 'ORDER_PAID', 'EMAIL', 'TR',
 'Siparişiniz alındı: {{orderNumber}}',
 'Merhaba {{customerName}},<br><br>{{orderNumber}} numaralı siparişiniz başarıyla alındı. Toplam: {{orderTotal}} {{currencyIso}}.<br><br>Siparişinizi görüntülemek için: {{orderUrl}}',
 TRUE),
('11111111-1111-4111-8111-000000000002', 'cntpl_order_paid_en', 'ORDER_PAID', 'EMAIL', 'EN',
 'Your order is confirmed: {{orderNumber}}',
 'Hello {{customerName}},<br><br>Your order {{orderNumber}} has been confirmed. Total: {{orderTotal}} {{currencyIso}}.<br><br>View your order: {{orderUrl}}',
 TRUE),
('11111111-1111-4111-8111-000000000003', 'cntpl_order_shipped_tr', 'ORDER_SHIPPED', 'EMAIL', 'TR',
 'Siparişiniz kargoya verildi: {{orderNumber}}',
 'Merhaba {{customerName}},<br><br>{{orderNumber}} numaralı siparişiniz kargoya verildi.<br>Kargo firması: {{carrierName}}<br>Takip numarası: {{trackingNumber}}<br>Takip bağlantısı: {{trackingUrl}}',
 TRUE),
('11111111-1111-4111-8111-000000000004', 'cntpl_order_shipped_en', 'ORDER_SHIPPED', 'EMAIL', 'EN',
 'Your order has shipped: {{orderNumber}}',
 'Hello {{customerName}},<br><br>Your order {{orderNumber}} has shipped.<br>Carrier: {{carrierName}}<br>Tracking number: {{trackingNumber}}<br>Tracking link: {{trackingUrl}}',
 TRUE),
('11111111-1111-4111-8111-000000000005', 'cntpl_request_created_tr', 'ORDER_REQUEST_CREATED', 'EMAIL', 'TR',
 'Talebiniz alındı: {{orderNumber}}',
 'Merhaba {{customerName}},<br><br>{{orderNumber}} numaralı siparişiniz için {{requestType}} talebiniz alındı. Talep durumunu hesabınızdan takip edebilirsiniz: {{orderUrl}}',
 TRUE),
('11111111-1111-4111-8111-000000000006', 'cntpl_request_created_en', 'ORDER_REQUEST_CREATED', 'EMAIL', 'EN',
 'We received your request: {{orderNumber}}',
 'Hello {{customerName}},<br><br>We received your {{requestType}} request for order {{orderNumber}}. You can follow the status from your account: {{orderUrl}}',
 TRUE),
('11111111-1111-4111-8111-000000000007', 'cntpl_request_approved_tr', 'ORDER_REQUEST_APPROVED', 'EMAIL', 'TR',
 'Talebiniz onaylandı: {{orderNumber}}',
 'Merhaba {{customerName}},<br><br>{{orderNumber}} numaralı siparişiniz için {{requestType}} talebiniz onaylandı. Not: {{decisionNote}}',
 TRUE),
('11111111-1111-4111-8111-000000000008', 'cntpl_request_approved_en', 'ORDER_REQUEST_APPROVED', 'EMAIL', 'EN',
 'Your request was approved: {{orderNumber}}',
 'Hello {{customerName}},<br><br>Your {{requestType}} request for order {{orderNumber}} was approved. Note: {{decisionNote}}',
 TRUE),
('11111111-1111-4111-8111-000000000009', 'cntpl_request_rejected_tr', 'ORDER_REQUEST_REJECTED', 'EMAIL', 'TR',
 'Talebiniz sonuçlandı: {{orderNumber}}',
 'Merhaba {{customerName}},<br><br>{{orderNumber}} numaralı siparişiniz için {{requestType}} talebiniz reddedildi. Not: {{decisionNote}}',
 TRUE),
('11111111-1111-4111-8111-000000000010', 'cntpl_request_rejected_en', 'ORDER_REQUEST_REJECTED', 'EMAIL', 'EN',
 'Your request was reviewed: {{orderNumber}}',
 'Hello {{customerName}},<br><br>Your {{requestType}} request for order {{orderNumber}} was rejected. Note: {{decisionNote}}',
 TRUE);
