CREATE TABLE commerce_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    order_number VARCHAR(40) NOT NULL,
    customer_id BIGINT NOT NULL,
    checkout_id BIGINT NOT NULL,
    payment_attempt_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    currency_iso VARCHAR(3) NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vat_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    shipping_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    shipping_method_code VARCHAR(50) NOT NULL,
    shipping_method_name VARCHAR(100) NOT NULL,
    delivery_address_uid VARCHAR(50) NOT NULL,
    billing_address_uid VARCHAR(50) NOT NULL,
    delivery_address_snapshot JSON NOT NULL,
    billing_address_snapshot JSON NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_transaction_id VARCHAR(191) NULL,
    legal_snapshot_status VARCHAR(30) NOT NULL,
    legal_snapshot_json JSON NULL,
    stock_deducted BOOLEAN NOT NULL DEFAULT FALSE,
    requires_attention BOOLEAN NOT NULL DEFAULT FALSE,
    attention_reason_key VARCHAR(191) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_order_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_order_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_order_number UNIQUE (order_number),
    CONSTRAINT uk_commerce_order_checkout UNIQUE (checkout_id),
    CONSTRAINT uk_commerce_order_payment_attempt UNIQUE (payment_attempt_id),
    CONSTRAINT fk_commerce_order_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_commerce_order_checkout FOREIGN KEY (checkout_id)
        REFERENCES commerce_checkouts(id) ON DELETE RESTRICT,
    CONSTRAINT fk_commerce_order_payment_attempt FOREIGN KEY (payment_attempt_id)
        REFERENCES commerce_payment_attempts(id) ON DELETE RESTRICT,
    INDEX idx_commerce_order_customer_status_created (customer_id, status, created_at),
    INDEX idx_commerce_order_requires_attention (requires_attention)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_order_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    order_id BIGINT NOT NULL,
    product_uid VARCHAR(50) NOT NULL,
    product_sku VARCHAR(100) NOT NULL,
    variant_uid VARCHAR(50) NOT NULL,
    variant_sku VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    unit_gross_price DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vat_rate DECIMAL(5,2) NOT NULL,
    line_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    line_vat_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_order_item_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_order_item_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_order_item_order_variant UNIQUE (order_id, variant_uid),
    CONSTRAINT fk_commerce_order_item_order FOREIGN KEY (order_id)
        REFERENCES commerce_orders(id) ON DELETE CASCADE,
    INDEX idx_commerce_order_item_order (order_id),
    INDEX idx_commerce_order_item_variant_uid (variant_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_order_number_counters (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    prefix VARCHAR(20) NOT NULL,
    order_date DATE NOT NULL,
    last_sequence INT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_order_number_counter_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_order_number_counter_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_order_number_counter_prefix_date UNIQUE (prefix, order_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
