CREATE TABLE commerce_customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL,
    email_normalized VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    gender VARCHAR(20) NULL,
    birth_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified_at DATETIME NULL,
    last_login_at DATETIME NULL,
    last_login_ip VARCHAR(45) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_customer_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_customer_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_customer_email_normalized UNIQUE (email_normalized),
    CONSTRAINT chk_commerce_customer_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'DELETED')),
    CONSTRAINT chk_commerce_customer_gender CHECK (gender IS NULL OR gender IN ('FEMALE', 'MALE', 'OTHER', 'UNSPECIFIED')),
    INDEX idx_commerce_customer_status (status),
    INDEX idx_commerce_customer_email_verified (email_verified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_customer_refresh_tokens (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    remember_me BOOLEAN NOT NULL DEFAULT FALSE,
    device_fingerprint VARCHAR(255) NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(512) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_customer_refresh_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_customer_refresh_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_customer_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_commerce_customer_refresh_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE CASCADE,
    INDEX idx_commerce_customer_refresh_customer (customer_id),
    INDEX idx_commerce_customer_refresh_expires (expires_at),
    INDEX idx_commerce_customer_refresh_revoked (revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_customer_consents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    consent_type VARCHAR(40) NOT NULL,
    accepted BOOLEAN NOT NULL,
    accepted_at DATETIME NOT NULL,
    source VARCHAR(50) NOT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(512) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_customer_consent_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_customer_consent_uid UNIQUE (uid),
    CONSTRAINT fk_commerce_customer_consent_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE CASCADE,
    CONSTRAINT chk_commerce_customer_consent_type CHECK (consent_type IN ('LEGAL_TERMS', 'PRIVACY_NOTICE', 'MARKETING_EMAIL', 'MARKETING_SMS', 'MARKETING_PHONE')),
    INDEX idx_commerce_customer_consent_customer (customer_id),
    INDEX idx_commerce_customer_consent_type (consent_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_customer_addresses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    label VARCHAR(100) NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    country_iso VARCHAR(2) NOT NULL DEFAULT 'TR',
    city VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NULL,
    postal_code VARCHAR(20) NULL,
    default_delivery BOOLEAN NOT NULL DEFAULT FALSE,
    default_billing BOOLEAN NOT NULL DEFAULT FALSE,
    invoice_type VARCHAR(20) NOT NULL DEFAULT 'INDIVIDUAL',
    company_name VARCHAR(200) NULL,
    tax_number VARCHAR(50) NULL,
    tax_office VARCHAR(100) NULL,
    invoice_identity_number VARCHAR(50) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_customer_address_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_customer_address_uid UNIQUE (uid),
    CONSTRAINT fk_commerce_customer_address_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE CASCADE,
    CONSTRAINT chk_commerce_customer_address_invoice_type CHECK (invoice_type IN ('INDIVIDUAL', 'CORPORATE')),
    INDEX idx_commerce_customer_address_customer (customer_id),
    INDEX idx_commerce_customer_address_delivery (customer_id, default_delivery),
    INDEX idx_commerce_customer_address_billing (customer_id, default_billing)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commerce_customer_social_identities (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_subject VARCHAR(191) NOT NULL,
    email_snapshot VARCHAR(254) NULL,
    linked_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_customer_social_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_customer_social_uid UNIQUE (uid),
    CONSTRAINT uk_commerce_customer_social_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT fk_commerce_customer_social_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE CASCADE,
    INDEX idx_commerce_customer_social_customer (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
