CREATE TABLE commerce_order_resolution_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    uid VARCHAR(50) NOT NULL,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    request_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    reason VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    previous_order_status VARCHAR(30) NOT NULL,
    requested_order_status VARCHAR(30) NOT NULL,
    decision_note VARCHAR(1000) NULL,
    decided_by_user_id BIGINT NULL,
    decided_by_email VARCHAR(191) NULL,
    decided_at DATETIME NULL,
    refund_status VARCHAR(30) NOT NULL,
    refund_provider VARCHAR(40) NULL,
    refund_reference VARCHAR(191) NULL,
    refund_failure_code VARCHAR(100) NULL,
    refund_failure_message_key VARCHAR(191) NULL,
    refund_attempted_at DATETIME NULL,
    refunded_at DATETIME NULL,
    stock_restored BIT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    CONSTRAINT uk_commerce_order_resolution_request_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_order_resolution_request_uid UNIQUE (uid),
    CONSTRAINT fk_commerce_order_resolution_request_order FOREIGN KEY (order_id)
        REFERENCES commerce_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_commerce_order_resolution_request_customer FOREIGN KEY (customer_id)
        REFERENCES commerce_customers(id) ON DELETE CASCADE,
    INDEX idx_commerce_order_resolution_request_order_status (order_id, status),
    INDEX idx_commerce_order_resolution_request_customer_created (customer_id, created_at),
    INDEX idx_commerce_order_resolution_request_status_created (status, created_at),
    INDEX idx_commerce_order_resolution_request_type_status_created (request_type, status, created_at),
    INDEX idx_commerce_order_resolution_request_refund_status (refund_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
