// Auto-generated by scripts/optimize-all.mjs — do not edit manually
export const HERO_LQIP = "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUABIAPxF8slSsJ6QjKAqpgCIJZQAALnUDpYn1FKaAAP7wyRqPZnWXT9s5APMZ9DPNNZwgAAA=";
