import { NAVIGATION_MODULES } from 'app/core/navigation/navigation-modules.constants';
import { AdminCraftNavigationItem } from './navigation.types';

export const DEFAULT_NAVIGATION_ITEMS: AdminCraftNavigationItem[] = [
    {
        id: 'apps',
        title: 'Yönetim',
        subtitle: 'Custom made application designs',
        type: 'group',
        icon: 'heroicons_outline:home',
        children: [
            {
                id: 'apps.custom.tenants',
                title: 'Tenant Yönetimi',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: 'tenants',
                requiredModule: null,
                requiredRole: 'SUPER_ADMIN',
            },
            {
                id: 'apps.custom.media',
                title: 'Medya Yönetimi',
                type: 'basic',
                icon: 'heroicons_outline:photo',
                link: 'media',
                requiredModule: NAVIGATION_MODULES.MEDIA,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.users',
                title: 'Kullanıcı Yönetimi',
                type: 'basic',
                icon: 'heroicons_outline:user-group',
                link: 'users',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.site',
                title: 'Site Yönetimi',
                type: 'basic',
                icon: 'heroicons_outline:globe-alt',
                link: 'site',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.pagebuilder',
                title: 'Page Builder',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-stack',
                link: 'pages',
                requiredModule: NAVIGATION_MODULES.PAGEBUILDER,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.pagebuilder.templates',
                title: 'Page Templates',
                type: 'basic',
                icon: 'heroicons_outline:document-duplicate',
                link: 'page-templates',
                requiredModule: NAVIGATION_MODULES.PAGEBUILDER,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.navigation',
                title: 'Navigasyon',
                type: 'basic',
                icon: 'heroicons_outline:bars-3',
                link: 'navigation',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.components',
                title: 'Components',
                type: 'basic',
                icon: 'heroicons_outline:cube',
                link: 'components',
                requiredModule: NAVIGATION_MODULES.COMPONENT_LIBRARY,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'apps.custom.products',
                title: 'Ürün Kataloğu',
                type: 'collapsable',
                icon: 'heroicons_outline:shopping-bag',
                requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                excludedRoles: ['SUPER_ADMIN'],
                children: [
                    {
                        id: 'apps.custom.products.list',
                        title: 'Ürünler',
                        type: 'basic',
                        icon: 'heroicons_outline:shopping-bag',
                        link: 'products',
                        requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                        excludedRoles: ['SUPER_ADMIN'],
                    },
                    {
                        id: 'apps.custom.products.types',
                        title: 'Ürün Tipleri',
                        type: 'basic',
                        icon: 'heroicons_outline:tag',
                        link: 'products/types',
                        requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                        excludedRoles: ['SUPER_ADMIN'],
                    },
                    {
                        id: 'apps.custom.products.categories',
                        title: 'Kategoriler',
                        type: 'basic',
                        icon: 'heroicons_outline:folder',
                        link: 'products/categories',
                        requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                        excludedRoles: ['SUPER_ADMIN'],
                    },
                ],
            },
        ],
    },
];
