import { NAVIGATION_MODULES } from 'app/core/navigation/navigation-modules.constants';
import { AdminCraftNavigationItem } from './navigation.types';

export const DEFAULT_NAVIGATION_ITEMS: AdminCraftNavigationItem[] = [
    {
        id: 'site-content',
        title: 'admin.nav.siteContent',
        subtitle: 'admin.nav.siteContentSubtitle',
        type: 'group',
        icon: 'heroicons_outline:globe-alt',
        children: [
            {
                id: 'site-content.dashboard',
                title: 'admin.nav.siteManagement',
                type: 'basic',
                icon: 'heroicons_outline:home',
                link: 'site',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'site-content.pages',
                title: 'admin.nav.pageBuilder',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-stack',
                link: 'pages',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'site-content.templates',
                title: 'admin.nav.pageTemplates',
                type: 'basic',
                icon: 'heroicons_outline:document-duplicate',
                link: 'page-templates',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'site-content.navigation',
                title: 'admin.nav.navigation',
                type: 'basic',
                icon: 'heroicons_outline:bars-3',
                link: 'navigation',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
        ],
    },
    {
        id: 'media-components',
        title: 'admin.nav.mediaComponents',
        subtitle: 'admin.nav.mediaComponentsSubtitle',
        type: 'group',
        icon: 'heroicons_outline:photo',
        children: [
            {
                id: 'media-components.media',
                title: 'admin.nav.mediaManagement',
                type: 'basic',
                icon: 'heroicons_outline:photo',
                link: 'media',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'media-components.library',
                title: 'admin.nav.componentCatalog',
                type: 'basic',
                icon: 'heroicons_outline:cube',
                link: 'components',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'media-components.types',
                title: 'admin.nav.componentTypes',
                type: 'basic',
                icon: 'heroicons_outline:tag',
                link: 'components/types',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
        ],
    },
    {
        id: 'product-catalog',
        title: 'admin.nav.productCatalog',
        subtitle: 'admin.nav.productCatalogSubtitle',
        type: 'group',
        icon: 'heroicons_outline:shopping-bag',
        children: [
            {
                id: 'product-catalog.products',
                title: 'admin.nav.products',
                type: 'basic',
                icon: 'heroicons_outline:shopping-bag',
                link: 'products',
                requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'product-catalog.types',
                title: 'admin.nav.productTypes',
                type: 'basic',
                icon: 'heroicons_outline:tag',
                link: 'products/types',
                requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'product-catalog.categories',
                title: 'admin.nav.categories',
                type: 'basic',
                icon: 'heroicons_outline:folder',
                link: 'products/categories',
                requiredModule: NAVIGATION_MODULES.PRODUCT_CATALOG,
                excludedRoles: ['SUPER_ADMIN'],
            },
        ],
    },
    {
        id: 'administration',
        title: 'admin.nav.administration',
        subtitle: 'admin.nav.administrationSubtitle',
        type: 'group',
        icon: 'heroicons_outline:user-group',
        children: [
            {
                id: 'administration.users',
                title: 'admin.nav.userManagement',
                type: 'basic',
                icon: 'heroicons_outline:user-group',
                link: 'users',
                requiredModule: NAVIGATION_MODULES.CORE,
                excludedRoles: ['SUPER_ADMIN'],
            },
            {
                id: 'administration.impex',
                title: 'admin.nav.impex',
                type: 'basic',
                icon: 'heroicons_outline:code-bracket',
                link: 'impex',
                requiredModule: NAVIGATION_MODULES.CORE,
                requiredRole: 'TENANT_ADMIN',
            },
            {
                id: 'administration.mail-marketing',
                title: 'admin.nav.mailMarketing',
                type: 'basic',
                icon: 'heroicons_outline:envelope',
                link: 'mail-marketing',
                requiredModule: NAVIGATION_MODULES.MAIL_MARKETING,
                requiredRole: 'TENANT_ADMIN',
            },
        ],
    },
    {
        id: 'platform',
        title: 'admin.nav.platform',
        subtitle: 'admin.nav.platformSubtitle',
        type: 'group',
        icon: 'heroicons_outline:cog-6-tooth',
        requiredRole: 'SUPER_ADMIN',
        children: [
            {
                id: 'platform.dashboard',
                title: 'admin.nav.platformDashboard',
                type: 'basic',
                icon: 'heroicons_outline:chart-bar-square',
                link: 'platform-dashboard',
                requiredModule: null,
                requiredRole: 'SUPER_ADMIN',
            },
            {
                id: 'platform.tenants',
                title: 'admin.nav.tenantManagement',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: 'tenants',
                requiredModule: null,
                requiredRole: 'SUPER_ADMIN',
            },
            {
                id: 'platform.settings',
                title: 'admin.nav.platformSettings',
                type: 'basic',
                icon: 'heroicons_outline:cog-6-tooth',
                link: 'platform-settings',
                requiredModule: null,
                requiredRole: 'SUPER_ADMIN',
            },
            {
                id: 'platform.mail',
                title: 'admin.nav.platformMail',
                type: 'basic',
                icon: 'heroicons_outline:envelope-open',
                link: 'platform-mail',
                requiredModule: null,
                requiredRole: 'SUPER_ADMIN',
            },
        ],
    },
];
