spring:
  application:
    name: AdminCraft CMS

  # Veritabanı Yapılandırması
  datasource:
    url: jdbc:mysql://localhost:3306/admincraft?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Yapılandırması
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  # Thymeleaf Yapılandırması
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # Spring Security Yapılandırması
  security:
    user:
      name: admin
      password: admin

# Sunucu Yapılandırması
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Loglama Yapılandırması
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.admincraft: DEBUG
    org.hibernate: INFO

# JWT Yapılandırması
app:
  jwt:
    secret: admincraft-jwt-super-secret-key-should-be-longer-in-production
    expiration-ms: 86400000 # 24 saat

# Dosya Yükleme Yapılandırması
file:
  upload-dir: ./uploads